services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/code
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_NAME=${DATABASE_NAME}
      - DECIDIM_DATABASE_NAME=${DECIDIM_DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3000"
    depends_on:
      - pg
      - redis

  worker:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    environment:
      - DATABASE_HOST=pg
      - DATABASE_NAME=${DATABASE_NAME}
      - DECIDIM_DATABASE_NAME=${DECIDIM_DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - pg
      - redis
    command: bundle exec sidekiq

  pg:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=decidim_production
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  bundle:
  node_modules:
  pg-data:
  redis-data:
